[file]
pathName = "/home/henio/neoway/especializacao_tcc/files/test_file_100K.csv"
separator = ","

[processing]
numberOfThreads = 40
batchSizeCommit = 500
validateLineByLine = true #true to validate parameters length, line by line

[database]
[database.postgres]
driver = "postgres"
user = "x"
password = "x"
port = "x"
dbname = "x"
host = "x"
maxOpenConns = 50
maxIdleConns = 10
schemaOutput = "x" #schema to save imported data
tableOutput = "x" #table to save imported data
[database.mongo]
#to do