[file]
pathName = "/home/henio/neoway/especializacao_tcc/files/test_file_100K.csv"
separator = ","

[processing]
numberOfThreads = 40
batchSizeCommit = 500
validateLineByLine = true

[database]
[database.postgres]
driver = "postgres"
user = "x"
password = "x"
port = "x"
dbname = "x"
host = "x"
maxOpenConns = 50
maxIdleConns = 10
schemaOutput = "testes_henio"
tableOutput = "file_imported"
[database.mongo]