 [database]
 #[postgres]
driver = "postgres"
user = "x"
password = "x"
port = "x"
dbname = "repositorio"
host = "x"
maxOpenConns = 50
maxIdleConns = 10
schemaOutput = "testes_henio"
tableOutput = "file_imported"

[file]
pathName = "/home/henio/go/src/file_etl_importer/test_file_10K.csv"
separator = ","

[processing]
numberOfThreads = 20
batchSizeCommit = 1000